=== davidegironi/appdressbook/api/docs/get_appdressbookcontacts-mode=l.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Contact list",
  "description": "RESTful GET appdressbookcontacts?mode=l route",
  "properties": {
    "persons": {
      "type": "array",
      "title": "List of persons",
      "items": [
        {
          "type": "object",
          "title": "Person informations",
          "properties": {
            "id": {
              "type": "integer",
              "title": "Person unique id"
            },
            "code": {
              "type": "string",
              "title": "Person unique code"
            },
            "firstname": {
              "type": "string",
              "title": "Person firstname"
            },
            "lastname": {
              "type": "string",
              "title": "Person lastname"
            },
            "locationcode": {
              "type": [
                "string",
                "null"
              ],
              "title": "Person location by code"
            },
            "companycode": {
              "type": [
                "string",
                "null"
              ],
              "title": "Person company by code"
            },
            "rolecode": {
              "type": [
                "string",
                "null"
              ],
              "title": "Person role by code"
            },
            "contacts": {
              "type": "array",
              "title": "List of person contacts",
              "items": [
                {
                  "type": "object",
                  "title": "Contact information",
                  "properties": {
                    "code": {
                      "type": "string",
                      "title": "Contact by code"
                    },
                    "value": {
                      "type": "string",
                      "title": "Contact value"
                    }
                  },
                  "required": [
                    "code",
                    "value"
                  ]
                }
              ]
            }
          },
          "required": [
            "id",
            "code",
            "firstname",
            "lastname",
            "contacts"
          ]
        }
      ]
    },
    "contacttypes": {
      "type": "array",
      "title": "List of type of contacts",
      "items": [
        {
          "type": "object",
          "title": "Contact type information",
          "properties": {
            "code": {
              "type": "string",
              "title": "Contact unique code"
            },
            "name": {
              "type": "string",
              "title": "Contact descriptive name"
            },
            "color": {
              "type": [
                "string",
                "null"
              ],
              "title": "Contact color in hex format"
            },
            "type": {
              "type": "string",
              "title": "Contact type, app link openable types are [email|phone]"
            }
          },
          "required": [
            "code",
            "name",
            "type"
          ]
        }
      ]
    },
    "companytypes": {
      "type": "array",
      "title": "List of type of companies",
      "items": [
        {
          "type": "object",
          "title": "Company type information",
          "properties": {
            "code": {
              "type": "string",
              "title": "Company unique code"
            },
            "name": {
              "type": "string",
              "title": "Company descriptive name"
            },
            "color": {
              "type": [
                "string",
                "null"
              ],
              "title": "Company color, in hex format"
            }
          },
          "required": [
            "code",
            "name"
          ]
        }
      ]
    },
    "roletypes": {
      "type": "array",
      "title": "List of type of roles",
      "items": [
        {
          "type": "object",
          "title": "Role type information",
          "properties": {
            "code": {
              "type": "string",
              "title": "Role unique code"
            },
            "name": {
              "type": "string",
              "title": "Role descriptive name"
            },
            "color": {
              "type": [
                "string",
                "null"
              ],
              "title": "Role color, in hex format"
            }
          },
          "required": [
            "code",
            "name"
          ]
        }
      ]
    },
    "locationtypes": {
      "type": "array",
      "title": "List of type of locations",
      "items": [
        {
          "type": "object",
          "title": "Location type information",
          "properties": {
            "code": {
              "type": "string",
              "title": "Location unique code"
            },
            "name": {
              "type": "string",
              "title": "Location descriptive name"
            },
            "color": {
              "type": [
                "string",
                "null"
              ],
              "title": "Location color, in hex format"
            }
          },
          "required": [
            "code",
            "name"
          ]
        }
      ]
    },
    "hash": {
      "type": "string",
      "title": "Contact list hashcode"
    }
  },
  "required": [
    "persons",
    "contacttypes",
    "companytypes",
    "roletypes",
    "locationtypes",
    "hash"
  ]
}

=== davidegironi/appdressbook/appdressbookapisample/samplecontacts.json
{
	"persons": [
		{
      "id": 1,
			"code": "PAL",
			"firstname": "Ward",
			"lastname": "Palacio",
			"locationcode": null,
			"companycode": "MC",
			"roleinfo": null,
			"rolecode": null,
			"contacts": [
				{
					"code": "CE",
					"value": "ward.palacio@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+1-5855072888"
				},
				{
					"code": "CM",
					"value": "+1-5166472404"
				},
				{
					"code": "AD",
					"value": "7292 Dictum Av. San Antonio MI 47096"
				}
			]
		},
		{
      "id": 2,
			"code": "KRZ",
			"firstname": "Evelina",
			"lastname": "Kriz",
			"locationcode": "CDG",
			"companycode": "MC",
			"roleinfo": null,
			"rolecode": "OFC",
			"contacts": [
				{
					"code": "CE",
					"value": "evelina.kriz@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+33-0245291274"
				}
			]
		},
		{
      "id": 3,
			"code": "LUC",
			"firstname": "Roselia",
			"lastname": "Luca",
			"locationcode": "Office",
			"companycode": "MC",
			"roleinfo": null,
			"rolecode": "CHF",
			"contacts": [
				{
					"code": "CE",
					"value": "roselia.luca@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+39-2566716273"
				}
			]
		},
		{
      "id": 4,
			"code": "COB",
			"firstname": "Kenny",
			"lastname": "Coburn",
			"locationcode": "JFK",
			"companycode": "YC",
			"roleinfo": null,
			"rolecode": "CEO",
			"contacts": [
				{
					"code": "CE",
					"value": "kenny.coburn@yourcompany.com"
				}
			]
		},
		{
      "id": 5,
			"code": "LUN",
			"firstname": "Magdalene",
			"lastname": "Lunde",
			"locationcode": "JFK",
			"companycode": "MC",
			"roleinfo": "Chief Executive Officer",
			"rolecode": "CHF",
			"contacts": [
				{
					"code": "CE",
					"value": "magdalene.lunde@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+1-9149309763"
				}
			]
		},
		{
      "id": 6,
			"code": "FRE",
			"firstname": "Valerie",
			"lastname": "Frese De La Roche Por Lo Longo Name Longo De Longo",
			"locationcode": "CDG",
			"companycode": "MC",
			"roleinfo": null,
			"rolecode": "OFC",
			"contacts": [
				{
					"code": "CE",
					"value": "valerie.frase.delarocheporlolongonamelongodelongo@mycompany.com"
				}
			]
		}
	],
	"contacttypes": [
		{
			"code": "CE",
			"name": "Company Email",
			"color": null,
      "type": "email"
		},
		{
			"code": "CM",
			"name": "Company Mobile Phone",
			"color": null,
      "type": "phone"
		},
		{
			"code": "AD",
			"name": "Address",
			"color": null,
      "type": "address"
		}
	],
	"companytypes": [
		{
			"code": "MC",
			"name": "My Company",
			"color": "#c62828"
		},
		{
			"code": "YC",
			"name": "Your Company",
			"color": "#c6ff00"
		}
	],
	"roletypes": [
		{
			"code": "OFC",
			"name": "Office personnel",
			"color": "#c62828"
		},
		{
			"code": "CHF",
			"name": "Chef",
			"color": "#c6ff00"
		},
		{
			"code": "CEO",
			"name": "C.E.O.",
			"color": "#c6ff00"
		}
	],
	"locationtypes": [
		{
			"code": "JKF",
			"name": "John F. Kennedy International Airport",
			"color": "#547dbf"
		},
		{
			"code": "CDG",
			"name": "Charles de Gaulle Airport",
			"color": "#50b279"
		},
		{
			"code": "Office",
			"name": "Main office",
			"color": "#349619"
		}
	],
	"hash": "XWg1Trr9T2xVbYobSVgzBA=="
}

=== davidegironi/appdressbook/api/sampleapi/samplecontacts.json
{
	"persons": [
		{
			"id": 1,
			"code": "PAL",
			"firstname": "Ward",
			"lastname": "Palacio",
			"locationcode": null,
			"companycode": "MC",
			"rolecode": null,
			"contacts": [
				{
					"code": "CE",
					"value": "ward.palacio@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+1-5855072888"
				},
				{
					"code": "CM",
					"value": "+1-5166472404"
				},
				{
					"code": "AD",
					"value": "7292 Dictum Av. San Antonio MI 47096"
				}
			]
		},
		{
			"id": 2,
			"code": "KRZ",
			"firstname": "Evelina",
			"lastname": "Kriz",
			"locationcode": "CDG",
			"companycode": "MC",
			"rolecode": "OFC",
			"contacts": [
				{
					"code": "CE",
					"value": "evelina.kriz@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+33-0245291274"
				}
			]
		},
		{
			"id": 3,
			"code": "LUC",
			"firstname": "Roselia",
			"lastname": "Luca",
			"locationcode": "Office",
			"companycode": "MC",
			"rolecode": "CFO",
			"contacts": [
				{
					"code": "CE",
					"value": "roselia.luca@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+39-2566716273"
				}
			]
		},
		{
			"id": 4,
			"code": "COB",
			"firstname": "Kenny",
			"lastname": "Coburn",
			"locationcode": "JFK",
			"companycode": "YC",
			"rolecode": "CEO",
			"contacts": [
				{
					"code": "CE",
					"value": "kenny.coburn@yourcompany.com"
				}
			]
		},
		{
			"id": 5,
			"code": "LUN",
			"firstname": "Magdalene",
			"lastname": "Lunde",
			"locationcode": "JFK",
			"companycode": "MC",
			"rolecode": "CTO",
			"contacts": [
				{
					"code": "CE",
					"value": "magdalene.lunde@mycompany.com"
				},
				{
					"code": "CM",
					"value": "+1-9149309763"
				}
			]
		},
		{
			"id": 6,
			"code": "FRE",
			"firstname": "Valerie",
			"lastname": "Frese De La Roche Por Lo Longo Name Longo De Longo",
			"locationcode": "CDG",
			"companycode": "MC",
			"rolecode": "OFC",
			"contacts": [
				{
					"code": "CE",
					"value": "valerie.frase.delarocheporlolongonamelongodelongo@mycompany.com"
				}
			]
		},
		{
			"id": 7,
			"code": "PIN",
			"firstname": "Michael",
			"lastname": "Pindru",
			"locationcode": null,
			"companycode": "MC",
			"rolecode": "OFC",
			"contacts": []
		}
	],
	"contacttypes": [
		{
			"code": "CE",
			"name": "Company Email",
			"color": null,
			"type": "email"
		},
		{
			"code": "CM",
			"name": "Company Mobile Phone",
			"color": null,
			"type": "phone"
		},
		{
			"code": "AD",
			"name": "Address",
			"color": null,
			"type": "address"
		}
	],
	"companytypes": [
		{
			"code": "MC",
			"name": "My Company",
			"color": "#c62828"
		},
		{
			"code": "YC",
			"name": "Your Company",
			"color": "#c6ff00"
		}
	],
	"roletypes": [
		{
			"code": "OFC",
			"name": "Office personnel",
			"color": "#c62828"
		},
		{
			"code": "CFO",
			"name": "Chief Financial Officer",
			"color": "#c6ff00"
		},
		{
			"code": "CTO",
			"name": "Chief Technology Officer",
			"color": "#c6ff00"
		},
		{
			"code": "CEO",
			"name": "Chief Executive Officer",
			"color": "#c6ff00"
		}
	],
	"locationtypes": [
		{
			"code": "JKF",
			"name": "John F. Kennedy International Airport",
			"color": "#547dbf"
		},
		{
			"code": "CDG",
			"name": "Charles de Gaulle Airport",
			"color": "#50b279"
		},
		{
			"code": "Office",
			"name": "Main office",
			"color": "#349619"
		}
	],
	"hash": "XWg1Trr9T2xVbYobSVgzBB=="
}
